

#if !defined GENERATED_VERSION_H
#define GENERATED_VERSION_H

#define CMGUI_NAME_STRING "OpenCMZN(cmgui)"
#define CMGUI_VERSION_STRING "@CMGUI_VERSION_STRING@"
#define CMGUI_DATETIME_STRING "@CMGUI_DATETIME_STRING@"
#define CMGUI_COPYRIGHT_STRING "Copyright 1996-2013, Auckland UniServices Ltd."
#define CMGUI_SVN_REVISION_STRING "@CMGUI_SVN_REVISION_STRING@"
#define CMGUI_BUILD_STRING "@CMGUI_BUILD_STRING@"

#endif

